version: '3.8'

services:
  api:
    container_name: MiniBlog
    build: .
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    environment:
      - JWT_SECRET_KEY=sadasdsadasd
      - DATABASE_URL=mysql+pymysql://miniblog:miniblog@db/appblog
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appblog
      MYSQL_USER: miniblog
      MYSQL_PASSWORD: miniblog
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: